nix/develop/local:
	nix develop --extra-experimental-features nix-command --extra-experimental-features flakes

nix/develop/remote:
	nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --refresh github:ottowhite/nix-dev#default --command echo "Configuration synchronized"

# test -n "$NIX_GCROOT" || nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --refresh github:ottowhite/nix-dev#default --command echo "Configuration synchronized"